// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PICMate.Api.Data;

#nullable disable

namespace PICMate.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518051005_AddRefreshTokenAndSecurity")]
    partial class AddRefreshTokenAndSecurity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PICMate.Api.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "👤",
                            Text = "Võ Thị E đã đăng ký tài khoản mới",
                            Time = "5 phút trước",
                            Type = "new_user"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "📦",
                            Text = "Đơn hàng BK-20251225-010 được tạo mới",
                            Time = "12 phút trước",
                            Type = "booking"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "⚠️",
                            Text = "Khiếu nại mới từ Trần Thị B",
                            Time = "3 giờ trước",
                            Type = "dispute"
                        });
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JoinDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalBookings")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Email = "nguyenvana@email.com",
                            JoinDate = "2025-01-15",
                            Name = "Nguyễn Văn A",
                            TotalBookings = 12,
                            TotalSpent = 2400000m,
                            Type = "Khách hàng"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Email = "tranthib@email.com",
                            JoinDate = "2025-02-20",
                            Name = "Trần Thị B",
                            TotalBookings = 8,
                            TotalSpent = 1600000m,
                            Type = "Khách hàng"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Email = "trongdao@email.com",
                            JoinDate = "2024-11-10",
                            Name = "Đào Nguyên Trọng",
                            TotalBookings = 45,
                            TotalSpent = 0m,
                            Type = "Phone-Grapher"
                        });
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.Booking", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotographerAvatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhotographerId")
                        .HasColumnType("integer");

                    b.Property<string>("PhotographerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = "BK-20251215-001",
                            Date = "2025-12-20",
                            Location = "Cafe The Coffee House, Quận 1",
                            Note = "Concept: Korean casual",
                            PhotographerAvatar = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face",
                            PhotographerId = 1,
                            PhotographerName = "Đào Nguyên Trọng",
                            Service = "Chụp ảnh sống ảo",
                            Status = "completed",
                            Time = "14:00",
                            Total = 200000m
                        },
                        new
                        {
                            Id = "BK-20251218-002",
                            Date = "2025-12-25",
                            Location = "Phố đi bộ Nguyễn Huệ",
                            Note = "Content review cafe + ăn vặt",
                            PhotographerAvatar = "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face",
                            PhotographerId = 3,
                            PhotographerName = "Bảo Vũ",
                            Service = "Quay TikTok",
                            Status = "confirmed",
                            Time = "09:00",
                            Total = 400000m
                        });
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.BookingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BookingStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "warning",
                            Key = "pending",
                            Label = "Chờ xác nhận"
                        },
                        new
                        {
                            Id = 2,
                            Color = "info",
                            Key = "confirmed",
                            Label = "Đã nhận"
                        },
                        new
                        {
                            Id = 3,
                            Color = "info",
                            Key = "in_progress",
                            Label = "Đang thực hiện"
                        },
                        new
                        {
                            Id = 4,
                            Color = "success",
                            Key = "completed",
                            Label = "Hoàn thành"
                        },
                        new
                        {
                            Id = 5,
                            Color = "danger",
                            Key = "cancelled",
                            Label = "Đã hủy"
                        });
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.DemoAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Redirect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DemoAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop&crop=face",
                            Email = "khach@picmate.vn",
                            Name = "Nguyễn Văn Khách",
                            Password = "123456",
                            Redirect = "/dashboard",
                            Role = "customer"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "/Trong.jpg",
                            Email = "photographer@picmate.vn",
                            Name = "Đào Nguyên Trọng",
                            Password = "123456",
                            Redirect = "/dashboard/photographer",
                            Role = "photographer"
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "",
                            Email = "admin@picmate.vn",
                            Name = "Admin PICMate",
                            Password = "admin123",
                            Redirect = "/admin",
                            Role = "admin"
                        });
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.Dispute", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Against")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgainstAvatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reporter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReporterAvatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Disputes");

                    b.HasData(
                        new
                        {
                            Id = "DP-001",
                            Against = "Đào Nguyên Trọng",
                            AgainstAvatar = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face",
                            Amount = 200000m,
                            Date = "2025-12-18",
                            OrderId = "BK-20251215-001",
                            Priority = "high",
                            Reason = "Thợ chụp đến muộn 30 phút",
                            Reporter = "Nguyễn Văn A",
                            ReporterAvatar = "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop&crop=face",
                            Status = "pending"
                        },
                        new
                        {
                            Id = "DP-002",
                            Against = "Bảo Vũ",
                            AgainstAvatar = "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face",
                            Amount = 400000m,
                            Date = "2025-12-20",
                            OrderId = "BK-20251218-002",
                            Priority = "urgent",
                            Reason = "Yêu cầu hoàn tiền do thợ hủy đơn",
                            Reporter = "Trần Thị B",
                            ReporterAvatar = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face",
                            Status = "pending"
                        });
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.FavoritePhotographer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PhotographerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FavoritePhotographers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PhotographerId = 1
                        },
                        new
                        {
                            Id = 2,
                            PhotographerId = 3
                        },
                        new
                        {
                            Id = 3,
                            PhotographerId = 5
                        });
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.MembershipFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MembershipPlanId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MembershipPlanId");

                    b.ToTable("MembershipFeatures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MembershipPlanId = 1,
                            Text = "Đặt lịch thợ chụp"
                        },
                        new
                        {
                            Id = 2,
                            MembershipPlanId = 1,
                            Text = "Chat với thợ"
                        },
                        new
                        {
                            Id = 3,
                            MembershipPlanId = 2,
                            Text = "Tất cả tính năng Basic"
                        },
                        new
                        {
                            Id = 4,
                            MembershipPlanId = 2,
                            Text = "Giảm 10% dịch vụ"
                        },
                        new
                        {
                            Id = 5,
                            MembershipPlanId = 3,
                            Text = "Tất cả tính năng Premium"
                        },
                        new
                        {
                            Id = 6,
                            MembershipPlanId = 3,
                            Text = "Giảm 20% dịch vụ"
                        });
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.MembershipPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Popular")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("MembershipPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Basic",
                            Popular = false,
                            Price = 0m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Premium",
                            Popular = true,
                            Price = 99000m
                        },
                        new
                        {
                            Id = 3,
                            Name = "VIP",
                            Popular = false,
                            Price = 199000m
                        });
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.MessageThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Online")
                        .HasColumnType("boolean");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Unread")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face",
                            LastMessage = "Ok em, mai 2h chiều mình gặp nhau nhé!",
                            Name = "Đào Nguyên Trọng",
                            Online = true,
                            Time = "10:30",
                            Unread = 2
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face",
                            LastMessage = "Ảnh đã chỉnh xong rồi nha.",
                            Name = "Bảo Vũ",
                            Online = true,
                            Time = "Hôm qua",
                            Unread = 0
                        });
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.Photographer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoverPhoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("HourlyPrice")
                        .HasColumnType("numeric");

                    b.Property<bool>("InstantBooking")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PerPhotoPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("TiktokPackagePrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Photographers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "/Trong.jpg",
                            Bio = "Chuyên chụp chân dung và lifestyle với phong cách Hàn Quốc nhẹ nhàng.",
                            CoverPhoto = "/Trong2.jpg",
                            HourlyPrice = 200000m,
                            InstantBooking = true,
                            IsOnline = true,
                            IsVerified = true,
                            Location = "Quận 1, TP.HCM",
                            Name = "Đào Nguyên Trọng",
                            PerPhotoPrice = 30000m,
                            Rating = 4.9m,
                            ReviewCount = 128,
                            TiktokPackagePrice = 500000m
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "/Dang.jpg",
                            Bio = "Phone-Grapher chuyên chụp vintage và cá tính.",
                            CoverPhoto = "/Dang22.jpg",
                            HourlyPrice = 180000m,
                            InstantBooking = false,
                            IsOnline = false,
                            IsVerified = true,
                            Location = "Quận 3, TP.HCM",
                            Name = "Bùi Phạm Hải Đăng",
                            PerPhotoPrice = 25000m,
                            Rating = 4.8m,
                            ReviewCount = 95,
                            TiktokPackagePrice = 450000m
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "/Bao.jpg",
                            Bio = "Chuyên outdoor & lifestyle photography.",
                            CoverPhoto = "/Bao22.jpg",
                            HourlyPrice = 150000m,
                            InstantBooking = true,
                            IsOnline = true,
                            IsVerified = true,
                            Location = "Quận 7, TP.HCM",
                            Name = "Bảo Vũ",
                            PerPhotoPrice = 20000m,
                            Rating = 4.7m,
                            ReviewCount = 73,
                            TiktokPackagePrice = 400000m
                        },
                        new
                        {
                            Id = 4,
                            Avatar = "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
                            Bio = "Street photographer & content creator.",
                            CoverPhoto = "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&h=400&fit=crop",
                            HourlyPrice = 170000m,
                            InstantBooking = true,
                            IsOnline = true,
                            IsVerified = false,
                            Location = "Quận Hoàn Kiếm, Hà Nội",
                            Name = "Hoàng Long",
                            PerPhotoPrice = 22000m,
                            Rating = 4.6m,
                            ReviewCount = 54,
                            TiktokPackagePrice = 480000m
                        },
                        new
                        {
                            Id = 5,
                            Avatar = "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face",
                            Bio = "Phone-Grapher phong cách Hàn Quốc.",
                            CoverPhoto = "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&h=400&fit=crop",
                            HourlyPrice = 250000m,
                            InstantBooking = false,
                            IsOnline = false,
                            IsVerified = true,
                            Location = "Quận Ba Đình, Hà Nội",
                            Name = "Bích Ngọc",
                            PerPhotoPrice = 35000m,
                            Rating = 4.9m,
                            ReviewCount = 112,
                            TiktokPackagePrice = 600000m
                        },
                        new
                        {
                            Id = 6,
                            Avatar = "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face",
                            Bio = "Chụp ảnh đêm đẹp nhất Sài Gòn.",
                            CoverPhoto = "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=400&fit=crop",
                            HourlyPrice = 160000m,
                            InstantBooking = true,
                            IsOnline = true,
                            IsVerified = true,
                            Location = "Quận 1, TP.HCM",
                            Name = "Quốc Bảo",
                            PerPhotoPrice = 20000m,
                            Rating = 4.5m,
                            ReviewCount = 41,
                            TiktokPackagePrice = 420000m
                        });
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.PhotographerPortfolioImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhotographerId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PhotographerId");

                    b.ToTable("PhotographerPortfolioImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&h=800&fit=crop",
                            PhotographerId = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&h=800&fit=crop",
                            PhotographerId = 1,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=600&h=800&fit=crop",
                            PhotographerId = 2,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&h=800&fit=crop",
                            PhotographerId = 3,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&h=800&fit=crop",
                            PhotographerId = 4,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&h=800&fit=crop",
                            PhotographerId = 5,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=600&h=800&fit=crop",
                            PhotographerId = 6,
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.PhotographerReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhotographerId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PhotographerId");

                    b.ToTable("PhotographerReviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
                            Date = "2025-12-15",
                            PhotographerId = 1,
                            Rating = 5,
                            Text = "Chụp quá đẹp luôn!",
                            User = "Hương Ly"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
                            Date = "2025-11-20",
                            PhotographerId = 1,
                            Rating = 5,
                            Text = "Book gấp mà vẫn chuyên nghiệp.",
                            User = "Thanh Tùng"
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face",
                            Date = "2025-12-20",
                            PhotographerId = 5,
                            Rating = 5,
                            Text = "Rất recommend!",
                            User = "Kim Anh"
                        });
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.PhotographerStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhotographerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PhotographerId");

                    b.ToTable("PhotographerStyles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hàn Quốc",
                            PhotographerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lifestyle",
                            PhotographerId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Minimal",
                            PhotographerId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Vintage",
                            PhotographerId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cá tính",
                            PhotographerId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Lifestyle",
                            PhotographerId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Lifestyle",
                            PhotographerId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "Minimal",
                            PhotographerId = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hàn Quốc",
                            PhotographerId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "Cá tính",
                            PhotographerId = 4
                        },
                        new
                        {
                            Id = 11,
                            Name = "Vintage",
                            PhotographerId = 4
                        },
                        new
                        {
                            Id = 12,
                            Name = "Hàn Quốc",
                            PhotographerId = 5
                        },
                        new
                        {
                            Id = 13,
                            Name = "Minimal",
                            PhotographerId = 5
                        },
                        new
                        {
                            Id = 14,
                            Name = "Cá tính",
                            PhotographerId = 6
                        },
                        new
                        {
                            Id = 15,
                            Name = "Vintage",
                            PhotographerId = 6
                        });
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.Preset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BeforeImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Downloads")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Presets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeforeImage = "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=500&fit=crop",
                            Category = "Da sáng Hàn",
                            Downloads = 1240,
                            Image = "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=500&fit=crop",
                            Name = "Seoul Sunrise",
                            Price = 49000m,
                            Rating = 4.8m
                        },
                        new
                        {
                            Id = 2,
                            BeforeImage = "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=400&h=500&fit=crop",
                            Category = "Cafe",
                            Downloads = 890,
                            Image = "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=500&fit=crop",
                            Name = "Café Latte",
                            Price = 39000m,
                            Rating = 4.6m
                        },
                        new
                        {
                            Id = 3,
                            BeforeImage = "https://images.unsplash.com/photo-1496440543089-3ef06b872312?w=400&h=500&fit=crop",
                            Category = "Ngoài trời",
                            Downloads = 2100,
                            Image = "https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=400&h=500&fit=crop",
                            Name = "Golden Hour",
                            Price = 59000m,
                            Rating = 4.9m
                        });
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DemoAccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DemoAccountId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.ServiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Chụp ảnh chân dung, ảnh đẹp, ảnh couple",
                            Icon = "📸",
                            Name = "Chụp ảnh sống ảo"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Chỉnh sửa ảnh theo phong cách",
                            Icon = "🎨",
                            Name = "Edit ảnh"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Quay video TikTok, Reels content",
                            Icon = "🎬",
                            Name = "Quay TikTok"
                        });
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.StyleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Styles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#FFB6C1",
                            Emoji = "🇰🇷",
                            Name = "Hàn Quốc"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#DEB887",
                            Emoji = "📷",
                            Name = "Vintage"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#FF6B6B",
                            Emoji = "🔥",
                            Name = "Cá tính"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#00b894",
                            Emoji = "🌿",
                            Name = "Lifestyle"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#a29bfe",
                            Emoji = "✨",
                            Name = "Minimal"
                        });
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
                            Name = "Hương Ly",
                            Rating = 5,
                            Role = "Khách hàng",
                            Text = "Book gấp trên PICMate mà thợ đến sau 15 phút."
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
                            Name = "Thanh Tùng",
                            Rating = 5,
                            Role = "Khách hàng",
                            Text = "Lần đầu dùng dịch vụ chụp ảnh qua app, ảnh ra đẹp."
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face",
                            Name = "Minh Anh",
                            Rating = 5,
                            Role = "Phone-Grapher",
                            Text = "PICMate giúp mình tìm được nhiều khách hàng hơn."
                        });
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.MembershipFeature", b =>
                {
                    b.HasOne("PICMate.Api.Domain.Entities.MembershipPlan", "MembershipPlan")
                        .WithMany("Features")
                        .HasForeignKey("MembershipPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipPlan");
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.PhotographerPortfolioImage", b =>
                {
                    b.HasOne("PICMate.Api.Domain.Entities.Photographer", "Photographer")
                        .WithMany("PortfolioImages")
                        .HasForeignKey("PhotographerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photographer");
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.PhotographerReview", b =>
                {
                    b.HasOne("PICMate.Api.Domain.Entities.Photographer", "Photographer")
                        .WithMany("Reviews")
                        .HasForeignKey("PhotographerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photographer");
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.PhotographerStyle", b =>
                {
                    b.HasOne("PICMate.Api.Domain.Entities.Photographer", "Photographer")
                        .WithMany("Styles")
                        .HasForeignKey("PhotographerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photographer");
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("PICMate.Api.Domain.Entities.DemoAccount", "DemoAccount")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("DemoAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemoAccount");
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.DemoAccount", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.MembershipPlan", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("PICMate.Api.Domain.Entities.Photographer", b =>
                {
                    b.Navigation("PortfolioImages");

                    b.Navigation("Reviews");

                    b.Navigation("Styles");
                });
#pragma warning restore 612, 618
        }
    }
}
